openapi: "3.0.0"
info:
  title: Indexd Application API
  description: >
    The Application API allows developers to pin and unpin slabs—collections of erasure-coded data shards—on the Sia network using Indexd. 
    Once pinned, Indexd ensures the data remains healthy and available by monitoring and maintaining the underlying storage.
  version: 2.0.0

servers:
  - url: http://localhost:9982/api

tags:
  - name: slabs
    description: List, pin, unpin and retrieve pinned slab details
  - name: hosts
    description: Fetch usable hosts

paths:
  /hosts:
    get:
      tags:
        - hosts
      summary: List usable hosts
      parameters:
          - name: limit
            in: query
            description: The maximum number of hosts to return
            schema:
              type: integer
              minimum: 1
              maximum: 500
              default: 100
          - name: offset
            in: query
            description: The number of hosts to skip
            schema:
              type: integer
              minimum: 0
              default: 0
      operationId: listHosts
      responses:
        '200':
          description: A list of usable hosts
          content:
            application/json:
              schema:
                type: object
                properties:
                  hosts:
                    type: array
                    items:
                      $ref: "#/components/schemas/HostInfo"

      x-codeSamples:
        - lang: Go
          label: Go
          source: |
            package main

            import (
              "context"
              app "go.sia.tech/indexd/app"
              "go.sia.tech/core/types"
            )

            func main() {
              var appKey types.PrivateKey
              client, err := app.NewClient("http://localhost:9982", appKey)
              hosts, err := client.Hosts(context.Background())
              // ...
            }

  /slabs:
    get:
      tags:
        - slabs
      summary: List all pinned slabs
      parameters:
          - name: limit
            in: query
            description: The maximum number of slab IDs to return
            schema:
              type: integer
              minimum: 1
              maximum: 500
              default: 100
          - name: offset
            in: query
            description: The number of slab IDs to skip
            schema:
              type: integer
              minimum: 0
              default: 0
      operationId: listSlabs
      responses:
        '200':
          description: A list of pinned slabs
          content:
            application/json:
              schema:
                type: object
                properties:
                  slabs:
                    type: array
                    items:
                      $ref: "#/components/schemas/SlabID"

      x-codeSamples:
        - lang: Go
          label: Go
          source: |
            package main

            import (
              "context"
              app "go.sia.tech/indexd/app"
              "go.sia.tech/core/types"
            )

            func main() {
              var appKey types.PrivateKey
              client, err := app.NewClient("http://localhost:9982", appKey)
              ids, err := client.SlabIDs(context.Background())
              // ...
            }
    post:
      tags:
        - slabs
      summary: Pin a slab to the indexer
      operationId: pinSlab
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                encryptionKey:
                  allOf:
                    - $ref: "#/components/schemas/EncryptionKey"
                    - description: The encryption key used to encrypt the shards
                minShards:
                  type: integer
                  minimum: 1
                  format: uint
                  description: The number of data shards a piece gets erasure-coded into
                sectors:
                  type: array
                  items:
                    type: object
                    properties:
                      root: 
                        allOf:
                          - $ref: "#/components/schemas/Hash256"
                          - description: The root of the sector
                      hostKey:
                        allOf:
                          - $ref: "#/components/schemas/PublicKey"
                          - description: The public key of the host that stores the sector
      responses:
        '201':
          description: Slab pinned successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  slabID:
                    allOf:
                      - $ref: "#/components/schemas/SlabID"
                      - description: The ID of the pinned slab

      x-codeSamples:
        - lang: Go
          label: Go
          source: |
            package main

            import (
              "context"
              app "go.sia.tech/indexd/app"
              "go.sia.tech/indexd/slabs"
              "go.sia.tech/core/types"
            )

            func main() {
              var appKey types.PrivateKey
              client, err := app.NewClient("http://localhost:9982", appKey)
              var params slabs.SlabPinParams
              id, err := client.PinSlab(context.Background(), params)
              // ...
            }

  /slabs/{slabid}:
    get:
      tags:
        - slabs
      summary: Get details of a pinned slab
      operationId: getSlab
      parameters:
        - name: slabid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Details of the pinned slab
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    allOf:
                      - $ref: "#/components/schemas/SlabID"
                      - description: The ID of the slab
                  encryptionKey:
                    allOf:
                      - $ref: "#/components/schemas/EncryptionKey"
                      - description: The encryption key used for the slab
                  minShards:
                    type: integer
                    description: The minimum number of shards required for the slab
                  sectors:
                    type: array
                    items:
                      type: object
                      properties:
                        root:
                          allOf:
                            - $ref: "#/components/schemas/Hash256"
                            - description: The root hash of the sector
                        hostKey:
                          allOf:
                            - $ref: "#/components/schemas/PublicKey"
                            - description: The public key of the host storing the sector
        '404':
          description: Slab not found

      x-codeSamples:
        - lang: Go
          label: Go
          source: |
            package main

            import (
              "context"
              app "go.sia.tech/indexd/app"
              "go.sia.tech/indexd/slabs"
              "go.sia.tech/core/types"
            )

            func main() {
              var appKey types.PrivateKey
              client, err := app.NewClient("http://localhost:9982", appKey)
              var id slabs.SlabID
              s, err := client.Slab(context.Background(), id)
              // ...
            }
    delete:
      tags:
        - slabs
      summary: Unpin a slab from the indexer
      operationId: unpinSlab
      parameters:
        - name: slabid
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Slab unpinned successfully

      x-codeSamples:
        - lang: Go
          label: Go
          source: |
            package main

            import (
              "context"
              app "go.sia.tech/indexd/app"
              "go.sia.tech/indexd/slabs"
              "go.sia.tech/core/types"
            )

            func main() {
              var appKey types.PrivateKey
              client, err := app.NewClient("http://localhost:9982", appKey)
              var id slabs.SlabID
              err = client.UnpinSlab(context.Background(), id)
              // ...
            }


components:
  schemas:
    EncryptionKey:
      $ref: './components.yml#/components/schemas/EncryptionKey'
    Hash256:
      $ref: './components.yml#/components/schemas/Hash256'
    HostInfo:
      $ref: './components.yml#/components/schemas/HostInfo'
    PublicKey:
      $ref: './components.yml#/components/schemas/PublicKey'
    SlabID:
      $ref: './components.yml#/components/schemas/SlabID'