name: Publish OpenAPI to Scalar Registry

permissions:
  contents: read

on:
  push:
    branches: [ master ]
    paths:
      - "openapi/**"
  workflow_dispatch:

jobs:
  admin:
    uses: SiaFoundation/workflows/.github/workflows/publish-openapi.yml@master
    with:
      slug: indexd-admin
      spec_path: openapi/admin.yml
      docs_slug: sia
    secrets:
      SCALAR_API_KEY: ${{ secrets.SCALAR_API_KEY }}

  app:
    uses: SiaFoundation/workflows/.github/workflows/publish-openapi.yml@master
    with:
      slug: indexd-app
      spec_path: openapi/app.yml
      docs_slug: sia
    secrets:
      SCALAR_API_KEY: ${{ secrets.SCALAR_API_KEY }}
